---
title: "data processing"
author: "Claire Herdeman"
date: "2/17/2019"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
---


```{r}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(magrittr)
library(scales)
library(here)
library(readxl)
library(zoo)
library(ggrepel)
library(RColorBrewer)
library(extrafont)
library(ggalluvial)
library(ggwordcloud)
library(sf)
library(ggmap)
library(tigris)
library(GGally)
library(cowplot)
library(data.tree)
library(rjson)
library(jsonlite)
source("utils.R")
source("load.R")
```


```{r}
alderman_contributions <- contribution %>% 
  mutate(ALDERMAN = "") %>%
  mutate(ALDERMAN = if_else(str_detect(RECIPIENT, 'ARENA'), 'JOHN ARENA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'AUSTIN'), 'CARRIE AUSTIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BEALE'), 'ANTHONY BEALE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BROOKINS'), 'HOWARD BROOKINS, JR.', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BURKE'), 'EDWARD BURKE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'BURNETT'), 'WALTER BURNETT, JR.', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CAPPLEMAN'), 'JAMES CAPPLEMAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CARDENAS'), 'GEORGE CARDENAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'COCHRAN'), 'WILLIE COCHRAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'CURTIS'), 'DERRICK CURTIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'DOWELL'), 'PAT DOWELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'EMANUEL'), 'EMANUEL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'ERVIN'), 'JASON ERVIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'FOULKES'), 'TONI FOULKES', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HAIRSTON'), 'LESLIE HAIRSTON', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HARRIS'), 'MICHELLE HARRIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'HOPKINS'), 'BRIAN HOPKINS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'KING'), 'SOPHIA KING', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'LAURINO'), 'MARGARET LAURINO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'LOPEZ'), 'RAYMOND LOPEZ', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MALDONADO'), 'ROBERTO MALDONADO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MELL'), 'DEBORAH MELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MITCHELL'), 'GREGORY MITCHELL', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MITTS'), 'EMMA MITTS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'JOE MOORE'), 'JOE MOORE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'DAVID MOORE'), 'DAVID MOORE', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MORENO'), 'JOE MORENO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'MUNOZ'), 'RICARDO MUNOZ', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'NAPOLITANO'), 'ANTHONY NAPOLITANO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, "O'CONNOR"), "PATRICK O'CONNOR", ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, "O'SHEA"), "MATTHEW O'SHEA", ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'OSTERMAN'), 'HARRY OSTERMAN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'PAWAR'), 'AMEYA PAWAR', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'QUINN'), 'MARTY QUINN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'RAMIREZ'), 'CARLOS RAMIREZ-ROSA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'REBOYRAS'), 'ARIEL REBOYRAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'REILLY'), 'BRENDAN REILLY', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SADLOWSKI'), 'SUSAN SADLOWSKI GARZA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SANTIAGO'), 'MILAGROS SANTIAGO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SAWYER'), 'RODERICK SAWYER', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SCOTT'), 'MICHAEL SCOTT, JR.', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SILVERSTEIN'), 'DEBRA SILVERSTEIN', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SMITH'), 'MICHELE SMITH', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SOLIS'), 'DANIEL SOLIS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'SPOSATO'), 'NICHOLAS SPOSATO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TABARES'), 'SILVANA TABARES', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TALIAFERRO'), 'CHRIS TALIAFERRO', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'THOMPSON'), 'PATRICK THOMPSON', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'TUNNEY'), 'THOMAS TUNNEY', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'VALENCIA'), 'ANNA VALENCIA', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'VILLEGAS'), 'GILBERT VILLEGAS', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'WAGUESPACK'), 'SCOTT WAGUESPACK', ALDERMAN),
         ALDERMAN = if_else(str_detect(RECIPIENT, 'ZALEWSKI'), 'MICHAEL ZALEWSKI', ALDERMAN)
         ) %>% 
  filter(ALDERMAN != "" & ALDERMAN != "EMANUEL" & ALDERMAN != "ANNA VALENCIA")

ald_totals <- alderman_contributions %>% filter(CONTRIBUTION_DATE > as.Date('2017-12-31') & CONTRIBUTION_DATE < as.Date('2019-01-01')) %>% group_by(ALDERMAN) %>% summarise(total = sum(AMOUNT))

ald_totals %<>% right_join(council, by = "ALDERMAN") %>% select(ALDERMAN, total, Ward)

ald_contrib_2018 <- alderman_contributions %>% filter(PERIOD_START > as.Date('2017-12-31') & PERIOD_START < as.Date('2019-01-01')) %>% group_by(ALDERMAN, LOBBYIST_NAME) %>% summarise(cont_to_aldermen = sum(AMOUNT)) 

comp_2018 <- compensation %>% filter(PERIOD_START > as.Date('2017-12-31') & PERIOD_START < as.Date('2019-01-01')) %>% group_by(LOBBYIST_NAME, CLIENT_NAME) %>% summarise(total_comp = sum(COMPENSATION_AMOUNT))

web <- ald_contrib_2018 %>% inner_join(comp_2018, by = "LOBBYIST_NAME")
web$pathString <- paste(web$ALDERMAN, 
                        web$LOBBYIST_NAME, 
                        web$CLIENT_NAME, 
                        sep = "/")
look <- as.Node(web)
print(look, "cont_to_aldermen", "total_comp")
a <- jsonlite::toJSON(as.list(look), force = TRUE)
write(a, here("data", "alc.json"))
write.csv(web, here("data", "alc.csv"))
```

```{r}
alderman_contributions
ward_boundaries$features$properties %<>% inner_join(ald_totals %>% 
                                           rename(ward = Ward,
                                                  alderman = ALDERMAN,
                                                 total = total) %>%
                                             mutate(ward = as.character(ward)), by = "ward")
ward_boundaries
write(toJSON(ward_boundaries), here("data", "ward_boundaries_update.geojson"))
```